### PR TITLE
Added Pamac tray icons

### PR DESCRIPTION
**Pull request by sergioad**
Hello I have added two new icons; these icons are for Pamac and I have tried to add the add and remove package icons for adding them to the UI but I did not found it's names

I hope this commit can be usefull to you :smile:

### CODE REVIEW

**Comment by anexation** [comment]
give me a few im resolving issues now with the square theme then i'll look at this

**Comment by sergioad** [comment]
Ok, thank you so much; I will be waiting for the updae :smile: remember that a major part of the icons are missing

**Comment by anexation** [comment]
yes i see that its not that the icons are missing is that numix didnt symlink alot of icons to respective places for each desktop but did on the circle one

**Comment by sergioad** [comment]
yep this is correct

**Pull request merged**
